return spectrum.Keybinding {
   { key = "h", action = "left", description = "Left direction."},
   { key = "j", action = "down", description = "Down direction."},
   { key = "k", action = "up", description = "Up direction."},
   { key = "l", action = "right", description = "Right direction."},
   { key = "left", action = "left", description = "Left direction."},
   { key = "down", action = "down", description = "Down direction."},
   { key = "up", action = "up", description = "Up direction."},
   { key = "right", action = "right", description = "Right direction."},
   { key = "h", mode = "grab", action = "left", description = "Left direction."},
   { key = "j", mode = "grab", action = "down", description = "Down direction."},
   { key = "k", mode = "grab", action = "up", description = "Up direction."},
   { key = "l", mode = "grab", action = "right", description = "Right direction."},
   { key = "left", mode = "grab", action = "left", description = "Left direction."},
   { key = "down", mode = "grab", action = "down", description = "Down direction."},
   { key = "up", mode = "grab", action = "up", description = "Up direction."},
   { key = "right", mode = "grab", action = "right", description = "Right direction."},
   { key = "z", action = "action1", description = "Use first item."},
   { key = "x", action = "action2", description = "Use second item."},
   { key = "c", action = "wait", description = "Wait."}
}
